version: '3.9'
services:
  # zookeeper:
  #         image: bitnami/zookeeper:latest
  #         ports:
  #             - 2181:2181
  #         environment:
  #             - ALLOW_ANONYMOUS_LOGIN=yes

  # kafka:
  #     image: bitnami/kafka:latest
  #     ports:
  #         - 9092:9092
  #         - 9093:9093
  #         - 29092:29092
  #     environment:
  #         # - KAFKA_CREATE_TOPICS="messages:1:1"
  #         KAFKA_BROKER_ID: 1
  #         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #         # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #         # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #         # - ALLOW_PLAINTEXT_LISTENER=yes
  #         # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
  #         # # - KAFKA_CFG_LISTENERS=CLIENT://:9092
  #         # # - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
  #         # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
  #         # - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
  #         # - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
  #         # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
  #         # - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
  #     depends_on:
  #         - zookeeper
  fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app/:/code
    environment:
          - KAFKA_HOST=kafka
          - KAFKA_PORT=9092
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: wurstmeister/kafka
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=kafka
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_ADVERTISED_PORT=9092
  #   hostname: kafka